baseurl = "https://ntk148v.github.io/blog"
languageCode = "en-us"
theme = "book"
pygmentsCodefences = true
enableEmoji = true
enableGitInfo = true

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/ntk148v/blog'
BookComments = true
BookServiceWorker = true
BookDateFormat = 'Jan 02, 2006'
BookEditPath = 'edit/master'
BookCommitPath = 'commit'

# set all headings to their default size (depending on browser settings)
# it's set to `true` by default
# oneHeadingSize = false
[markup]
codeFences = true
noClasses = false

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[markup.highlight]
style = 'monokailight'
noClasses = true
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[languages]

[languages.en]
languageName = "English"
title = "/home/kiennt"

[menu]
[[menu.after]]
name = "Notes"
url = "https://ntk148v.github.io/notes"
weight = 10
